import type { SampleBookText } from "./types";

const de: SampleBookText = {
  title: "Familie Schneider",
  subtitle: "Sieben Generationen einer Familie",
  years: "1846 — 2026",
  motto: "Glück auf und Brot im Haus",
  crest: { shape: "heater", division: "pale", field: "sable", field2: "or", ordinary: "none", ordinaryColor: "argent", charges: ["hammer", "wheat"], chargeColor: "gules", motto: "" },
  dedication: "Für Mia und Paul – damit sie wissen, woher sie kommen.\nUnd für Oma Uschi, die alles erzählt hat.",
  contents: "Inhalt",
  treeTitle: "Unsere Linie",
  relatives: 61,
  treeNote: "Die direkte Linie von Johann Schneider, Bauer im Westerwald, bis zu Mia und Paul. Im Stammbaum stehen noch einundsechzig weitere: Geschwister, ihre Ehepartner und Kinder.",
  line: [
    { h: ["Johann Schneider", "1846–1910"], w: ["Katharina Weber", "1850–1921"] },
    { h: ["Wilhelm Schneider", "1874–1938"], w: ["Anna Becker", "1878–1955"] },
    { h: ["Heinrich Schneider", "1902–1971"], w: ["Elisabeth Hoffmann", "1905–1993"] },
    { h: ["Karl-Heinz Schneider", "1932–2010"], w: ["Ursula Krüger", "1935–2019"] },
    { h: ["Michael Schneider", "1961"], w: ["Sabine Lehmann", "1963"] },
    { h: ["Jonas Schneider", "1990"], w: ["Elif Yılmaz", "1991"] },
  ],
  children: [["Mia", "2017"], ["Paul", "2020"]],
  family: {
    caption: "Familie Schneider, Gelsenkirchen, 1911",
    year: 1911, scene: "house",
    prompt: "Formal studio portrait of a German miner's family in the Ruhr, 1911: a father with a big moustache in a dark suit, a mother in a high-collared black dress seated, two boys in sailor suits and a girl with a large hair bow, a painted backdrop with a balustrade and a palm. Cabinet-card look.",
  },
  mapTitle: "Der Weg der Familie",
  mapNote: "Vom Dorf im Westerwald unter Tage ins Ruhrgebiet, über die Mauer hinweg nach Leipzig und Berlin – und am Ende nach Hamburg.",
  stops: [
    { name: "Westerwald", label: "der Hof bei Montabaur", lon: 7.83, lat: 50.44, year: 1846 },
    { name: "Gelsenkirchen", label: "Zeche und Bäckerei", lon: 7.09, lat: 51.51, year: 1896 },
    { name: "Leipzig", label: "Sabines Heimat", lon: 12.37, lat: 51.34, year: 1963 },
    { name: "Berlin", label: "die Nacht der Maueröffnung", lon: 13.4, lat: 52.52, year: 1989 },
    { name: "Hamburg", label: "heute zu Hause", lon: 9.99, lat: 53.55, year: 2015 },
  ],
  recipe: {
    chapter: "Traditionen",
    title: "Oma Uschis Streuselkuchen",
    who: "Ursula Schneider, geb. Krüger, 1935–2019",
    ingredientsTitle: "Man braucht",
    ingredients: ["500 g Mehl", "1 Würfel Hefe", "250 ml lauwarme Milch", "75 g Zucker", "75 g Butter", "1 Ei", "für die Streusel: 300 g Mehl, 200 g Zucker, 200 g Butter, Zimt"],
    text: "Hefe in der lauwarmen Milch auflösen, mit Mehl, Zucker, Butter und Ei zu einem glatten Teig kneten und zugedeckt eine Stunde gehen lassen. Auf ein gefettetes Blech ausrollen. Für die Streusel Mehl, Zucker und kalte Butter mit den Fingern verkrümeln, eine Prise Zimt dazu, dick auf dem Teig verteilen. Noch einmal zwanzig Minuten gehen lassen und bei 180 Grad backen, bis die Streusel goldgelb sind.",
    note: "Oma sagte: «Die Streusel müssen dicker sein als der Boden, sonst ist es kein Streuselkuchen.» Elif backt ihn jetzt jeden Sonntag – mit etwas Kardamom.",
    prompt: "A tray of German crumb cake (Streuselkuchen) cut into squares on a kitchen table with a floral oilcloth, a pot of coffee, Sunday porcelain cups and an old handwritten recipe booklet. Warm afternoon light.",
  },
  stories: [
    {
      scene: "village", year: 1880, chapter: "Ursprung", title: "Der Hof im Westerwald", who: "Johann Schneider, 1846–1910", caption: "Westerwald, 1880",
      prompt: "A small half-timbered farmhouse in a German village in the Westerwald around 1880: a muddy yard, a dung heap, chickens, a wooden cart, a farmer with a scythe, a church tower behind, rolling hills.",
      text: "Der älteste Schneider, den wir kennen, war Johann, Kleinbauer in einem Dorf bei Montabaur. Der Hof war so klein, dass er im Winter nebenbei als Steinhauer arbeitete. Er hatte acht Kinder, und nur der Älteste konnte den Hof erben. Johann soll gesagt haben, ein Schneider brauche keine Schere, sondern zwei Hände. Seine Taschenuhr – eine schwere Silberuhr mit Sprung im Glas – liegt heute bei Michael in der Schublade.",
      quote: "Wer früh aufsteht, dem gehört der Tag.",
    },
    {
      scene: "city", year: 1898, chapter: "Aufbruch", title: "Unter Tage", who: "Wilhelm Schneider, 1874–1938", caption: "Zeche, Gelsenkirchen, 1898",
      prompt: "A coal mine in the Ruhr around 1898: a riveted steel headframe with wheels, brick buildings, a group of miners with lamps and helmets after a shift, coal dust, a railway wagon, smoky sky.",
      text: "Mit zweiundzwanzig ging Wilhelm ins Ruhrgebiet, wo die Zechen Männer suchten. Er fuhr in Gelsenkirchen ein, wohnte zuerst als Kostgänger bei einer Bergmannsfamilie und schickte jeden Monat Geld ins Dorf. Den Gruß «Glück auf!» sagte er sein Leben lang auch beim Bäcker. Seine Frau Anna lernte er im Kirchenchor kennen; sie war die Einzige, die über seinen Westerwälder Dialekt nicht lachte.",
    },
    {
      scene: "city", year: 1923, chapter: "Schwere Jahre", title: "Brot für eine Milliarde", who: "Heinrich Schneider, 1902–1971", caption: "Gelsenkirchen, 1923",
      prompt: "A small German bakery shop around 1923: a baker in a white apron behind a wooden counter with loaves of bread, a queue of people in coats holding bundles of paper money, a shop sign in old lettering without readable text.",
      text: "Heinrich wollte nicht unter Tage. Er lernte Bäcker und eröffnete 1923 mit Elisabeth einen kleinen Laden – ausgerechnet im Jahr der Inflation. Ein Brot kostete im November eine Milliarde Mark, morgens anders als abends. Die Leute kamen mit Wäschekörben voller Scheine. Elisabeth schrieb die Preise mit Kreide und wischte sie zweimal am Tag weg. Einen dieser Geldscheine haben wir noch: hundert Milliarden Mark.",
      quote: "Brot backen kann man immer, Geld drucken nicht.",
    },
    {
      scene: "city", year: 1947, chapter: "Nach dem Krieg", title: "Trümmerjahre", who: "Karl-Heinz Schneider, 1932–2010", caption: "Gelsenkirchen, 1947",
      prompt: "A bombed-out German street in 1947: ruins of brick houses, women passing bricks hand to hand in a chain, a boy pulling a handcart with coal, a tram line, overcast sky.",
      text: "Als der Krieg zu Ende war, war Karl-Heinz dreizehn. Die Bäckerei lag in Trümmern, die Familie wohnte im Keller. Er sammelte Kohle von den Güterzügen und klopfte mit seiner Mutter Steine sauber, damit der Laden wieder aufgebaut werden konnte. Im Winter 1947 backte sein Vater das erste Brot im neuen Ofen. Karl-Heinz erzählte später, es habe nie wieder so gut gerochen.",
    },
    {
      scene: "field", year: 1962, chapter: "Wunderjahre", title: "Der Käfer", who: "Karl-Heinz und Ursula Schneider, 1962", caption: "Gardasee, 1962",
      prompt: "A pale blue Volkswagen Beetle parked at the shore of Lake Garda in 1962, a young German couple in sunglasses leaning on it, olive trees and mountains behind, a picnic basket, bright summer light.",
      text: "1962 kaufte Karl-Heinz einen gebrauchten hellblauen Käfer, und im Sommer fuhren er und Uschi zum ersten Mal über die Alpen nach Italien. Zwei Tage Fahrt, eine Nacht im Auto am Brenner, und dann der Gardasee. Uschi hatte nie das Meer gesehen und hielt den See zuerst dafür. Von dieser Reise stammt das Foto, das bei uns im Flur hängt – beide lachen, und der Käfer hat einen platten Reifen.",
    },
    {
      scene: "city", year: 1989, chapter: "Liebe", title: "Die Mauer", who: "Michael und Sabine Schneider, 1989", caption: "Berlin, 9. November 1989",
      prompt: "The Berlin Wall at night on 9 November 1989: a crowd of people in winter jackets climbing and celebrating on the wall, flashlights, a Trabant car, people hugging, festive chaos.",
      text: "Sabine kam aus Leipzig. Michael hatte sie 1987 bei einem Kirchentreffen kennengelernt und ihr zwei Jahre lang Briefe geschrieben, die manchmal geöffnet ankamen. Am 9. November 1989 stand er zufällig in Berlin, als die Grenze aufging. Drei Tage später saß Sabine mit ihrer Schwester im Trabi vor seiner Tür in Gelsenkirchen. Im Sommer darauf heirateten sie – mit Gästen aus Ost und West an einem Tisch.",
      voice: "Hören Sie, wie Michael es erzählt",
    },
    {
      scene: "house", year: 2015, chapter: "Heute", title: "Hamburg", who: "Jonas Schneider, 1990", caption: "Hamburg, 2015",
      prompt: "A young couple carrying moving boxes into an old brick apartment building in Hamburg in 2015, bicycles at the entrance, a little harbour crane visible in the distance, overcast northern light.",
      text: "Elif und ich haben uns im Studium in Bochum kennengelernt, in einer Vorlesung, die wir beide schwänzen wollten. 2015 zogen wir nach Hamburg, weil sie dort eine Stelle am Hafen bekam. Unsere Hochzeit war das erste Fest, auf dem meine Oma Uschi und Elifs Oma Ayşe nebeneinander saßen. Sie sprachen kaum eine gemeinsame Sprache und haben sich trotzdem den ganzen Abend Kuchenrezepte erklärt.",
    },
    {
      scene: "house", year: 2024, chapter: "Die nächste Generation", title: "Omas Stimme", who: "Jonas Schneider, 1990", caption: "Hamburg, 2024",
      prompt: "A bright Hamburg kitchen in the evening: a young father and two small children at a wooden table looking at an old photo album, a phone playing audio, a plate of crumb cake, warm lamp light.",
      text: "Ein Jahr bevor sie starb, habe ich Oma Uschi an drei Nachmittagen mit dem Handy aufgenommen. Sie erzählte von den Trümmern, vom Käfer und davon, wie Opa ihr den ersten Kuss erst nach dem dritten Kinobesuch gab. Jetzt will Mia abends «Omas Geschichte» hören. Sie hat ihre Urgroßmutter nie getroffen, aber sie lacht an denselben Stellen wie ich.",
      voice: "Oma Uschis Stimme, aufgenommen 2018",
    },
  ],
  endTitle: "Dieses Buch ist ein Beispiel",
  endText: "Die Schneiders sind erfunden, das Buch ist echt: So stellt Treename die Geschichten zusammen, die Ihre Familie mit ihrer Stimme erzählt – mit Stammbaum, Karte und Fotos. Ihres entsteht aus Ihren eigenen Geschichten.",
  colophon: "Das Familienbuch der Schneiders · gemacht mit Treename · 2026",
  photoNote: "Familie und Fotos in diesem Beispiel wurden zur Veranschaulichung erstellt.",
  ui: {
    facts: ["Generationen", "Menschen im Stammbaum", "Orte", "Geschichten"],
    back: "← Startseite", start: "Eigenes Buch beginnen", prev: "Zurück", next: "Weiter", open: "Buch öffnen",
    page: "Seite", of: "von", hint: "Blättern mit den Pfeiltasten, durch Wischen oder mit den Knöpfen", chapter: "Kapitel", listen: "Scannen und zuhören",
    eyebrow: "Beispielbuch", lead: "So kann das Buch Ihrer Familie aussehen: Geschichten, mit der Stimme erzählt, Stammbaum, Karte des Familienwegs und Fotos. Blättern Sie im Buch der erfundenen Familie Schneider.", cta: "Im Beispielbuch blättern",
  },
};
export default de;
