import type { SampleBookText } from "./types";

const en: SampleBookText = {
  title: "The Joneses",
  subtitle: "Seven generations of one family",
  years: "1848 — 2026",
  motto: "Sing while you work",
  crest: { shape: "heater", division: "plain", field: "gules", field2: "or", ordinary: "chief", ordinaryColor: "or", charges: ["music", "hammer", "hammer"], chargeColor: "argent", motto: "" },
  dedication: "For Seren and Owen, so they know where they come from.\nAnd for Nan Joan, who told it all before it was too late.",
  contents: "Contents",
  treeTitle: "Our line",
  relatives: 58,
  treeNote: "The direct line from Evan Jones, a collier in the Rhondda, to Seren and Owen. The family tree holds fifty-eight more: brothers, sisters, husbands, wives and their children.",
  line: [
    { h: ["Evan Jones", "1848–1911"], w: ["Margaret Price", "1852–1920"] },
    { h: ["David Jones", "1875–1940"], w: ["Mary Davies", "1879–1958"] },
    { h: ["William Jones", "1903–1972"], w: ["Elsie Hughes", "1906–1990"] },
    { h: ["Thomas Jones", "1931–2009"], w: ["Joan Evans", "1934–2021"] },
    { h: ["Gareth Jones", "1958"], w: ["Susan Clarke", "1960"] },
    { h: ["Rhys Jones", "1987"], w: ["Priya Shah", "1989"] },
  ],
  children: [["Seren", "2018"], ["Owen", "2021"]],
  family: {
    caption: "The Joneses, Treorchy, 1910",
    year: 1910, scene: "house",
    prompt: "Formal studio portrait of a Welsh mining family in 1910: a moustached father in his Sunday suit and flat cap, a mother in a high-collared dark dress, a teenage son, two daughters in white pinafores, a painted backdrop and a fern on a stand. Cabinet-card look.",
  },
  mapTitle: "The family's road",
  mapNote: "From a pit village in the Rhondda to the Cardiff docks, a classroom in Swansea, London and Manchester — never further than a few hours from home, and a whole world away.",
  stops: [
    { name: "Treorchy", label: "the pit and the chapel", lon: -3.51, lat: 51.66, year: 1848 },
    { name: "Cardiff", label: "the docks after the strike", lon: -3.18, lat: 51.48, year: 1926 },
    { name: "Swansea", label: "a teacher's first post", lon: -3.94, lat: 51.62, year: 1958 },
    { name: "London", label: "a bedsit and a band", lon: -0.13, lat: 51.51, year: 1982 },
    { name: "Manchester", label: "home now", lon: -2.24, lat: 53.48, year: 2012 },
  ],
  recipe: {
    chapter: "Traditions",
    title: "Nan Joan's Welsh cakes",
    who: "Joan Jones, née Evans, 1934–2021",
    ingredientsTitle: "You need",
    ingredients: ["225 g self-raising flour", "110 g butter", "85 g caster sugar", "a handful of currants", "1 egg", "a pinch of nutmeg", "a splash of milk"],
    text: "Rub the butter into the flour until it looks like breadcrumbs, then stir in the sugar, nutmeg and currants. Add the egg and just enough milk to make a firm dough. Roll it out to the thickness of your little finger and cut rounds with a glass. Cook them on a hot bakestone — or a heavy frying pan — three minutes a side, until golden. Dust with sugar while warm.",
    note: "Nan never weighed anything — “a cup of this, a knob of that”. Gareth stood next to her one Sunday with kitchen scales and wrote it down.",
    prompt: "A stack of freshly made Welsh cakes dusted with sugar on a cast-iron bakestone, a floral china plate, a cup of tea and an old handwritten recipe card on a wooden kitchen table. Soft daylight.",
  },
  stories: [
    {
      scene: "village", year: 1885, chapter: "Origins", title: "The pit village", who: "Evan Jones, 1848–1911", caption: "Treorchy, 1885",
      prompt: "A Welsh coal mining village in the Rhondda valley in the 1880s: terraced stone houses climbing a steep hillside, a colliery headframe and spoil heaps, miners with lamps walking home, chimney smoke, wet slate roofs.",
      text: "The first Jones we know by name went underground at the age of eleven. Evan worked forty years at the Abergorki pit, and the family still has his brass lamp, worn smooth where his thumb held it. On Sundays he walked his children to chapel twice and sang bass in a voice that, people said, could be heard at the bottom of the valley. He died in 1911 and is buried above Treorchy, looking down on the terrace where he lived.",
      quote: "Leave the coal in the pit and the worry at the door.",
    },
    {
      scene: "school", year: 1905, chapter: "Childhood", title: "The choir", who: "David Jones, 1875–1940", caption: "Treorchy Male Choir, 1905",
      prompt: "A Welsh male voice choir of about forty men in dark suits and bow ties posed on wooden benches outside a stone chapel around 1905, a conductor with a baton in the middle.",
      text: "David followed his father down the pit and into the choir. In 1905 the choir sang at the National Eisteddfod, and David travelled further from home than ever before, with his only good suit pressed under the mattress the night before. He brought back a china cup with a red dragon painted on it. The cup is chipped now, but Nan Joan kept it on the dresser until the day she died, and Seren drinks her milk from it on birthdays.",
    },
    {
      scene: "city", year: 1926, chapter: "Hard years", title: "1926", who: "William Jones, 1903–1972", caption: "Cardiff docks, 1926",
      prompt: "Cardiff docks in 1926: cargo steamships, cranes and coal tips, dockers in caps and waistcoats, stacks of timber, wet cobbles, a horse and cart, misty morning light.",
      text: "In the General Strike of 1926 the pits closed for seven months. The chapel ran a soup kitchen, and William, twenty-three, helped carry the pans. When the strike ended there was no job for him, so he walked to Cardiff with a friend — twenty-five miles in a day — and found work on the docks loading coal onto ships for Argentina. He used to say he left the valley with one shilling and a sandwich, and spent the shilling on the tram.",
    },
    {
      scene: "pier", year: 1930, chapter: "Love", title: "The dance at the Docks Hall", who: "Elsie Jones, née Hughes, 1906–1990", caption: "Cardiff, 1930",
      prompt: "A dance hall in Cardiff around 1930: couples in 1930s dresses and suits dancing, a small band on a stage with a piano and a saxophone, paper decorations, warm lamp light.",
      text: "Elsie worked in a biscuit factory and went dancing every Saturday at the Docks Hall. William could not dance at all, so he asked her to teach him. By the third Saturday he had stepped on her feet so often that she said she might as well marry him — and she did, in the spring of 1930. They lived in two rooms off Bute Street, and for their first anniversary William bought her a gramophone on the never-never.",
    },
    {
      scene: "house", year: 1941, chapter: "The war", title: "Under the stairs", who: "Thomas Jones, 1931–2009", caption: "Cardiff, 1941",
      prompt: "A Cardiff terraced street in 1941 after an air raid: a damaged house, rubble, a family with a pram and suitcases, an air-raid warden in a helmet, a corrugated Anderson shelter in a back garden, grey sky.",
      text: "Thomas was ten during the Cardiff Blitz. When the sirens went, the family squeezed into the cupboard under the stairs, and Elsie sang hymns so loudly that the children couldn't hear the bombs. One night in January 1941 the house two doors down was hit. In the morning Thomas found a toy soldier in the rubble and kept it for the rest of his life; it stood on his desk all the years he taught school.",
      quote: "Sing louder, and the bombs get quieter.",
    },
    {
      scene: "school", year: 1958, chapter: "Work", title: "Mr Jones, Standard Four", who: "Thomas and Joan Jones, 1958", caption: "Swansea, 1958",
      prompt: "A primary school classroom in Swansea in 1958: wooden desks with inkwells, children in grey jumpers, a young teacher in a tweed jacket at a blackboard with sums written on it, a map of the world on the wall.",
      text: "Thomas was the first Jones to stay at school past fourteen. After National Service he trained as a teacher and got his first post in Swansea, where he met Joan, the school secretary, who corrected the spelling in his reports. They married in 1958. For thirty-five years he taught Standard Four, and grown men would still stop him in the street and say, “Sir, you were the one who made me read.”",
    },
    {
      scene: "city", year: 1982, chapter: "Leaving home", title: "London", who: "Gareth Jones, 1958", caption: "London, 1982",
      prompt: "A London street in 1982: a red double-decker bus, a punk band's posters on a brick wall, young people in denim jackets outside a record shop, a black cab, an overcast sky.",
      text: "I went to London in 1982 with a guitar and a sleeping bag. I lived in a bedsit in Camden, played bass in a band nobody remembers, and worked nights sorting post at Mount Pleasant. That's where I met Susan — she was the supervisor and told me off for reading the postcards. My father didn't say much when I left Wales, but every Sunday a letter came, always ending the same way: “Eat properly. Dad.”",
      voice: "Listen to Gareth telling it",
    },
    {
      scene: "house", year: 2024, chapter: "The next generation", title: "Nan's voice", who: "Rhys Jones, 1987", caption: "Manchester, 2024",
      prompt: "A cosy Manchester living room in the evening: a young father with two small children on a sofa looking at an old photo album, a phone playing audio on the coffee table, a plate of Welsh cakes, warm lamp light.",
      text: "In 2019 I sat with Nan Joan at her kitchen table in Swansea and recorded her on my phone for three afternoons. She told me about the dances, the war, and Grandad Tom's terrible singing. She died two years later. Now Owen asks for “Nanna's story” at bedtime. He never met her, but he knows exactly how she laughs, and so will his children.",
      voice: "Nan Joan's voice, recorded in 2019",
    },
  ],
  endTitle: "This book is a sample",
  endText: "The Joneses are made up, but the book is real: this is how Treename puts together the stories your family tells by voice, with the tree, the map and the photographs. Yours will be made from your own stories.",
  colophon: "The Jones family book · made with Treename · 2026",
  photoNote: "The family and the photographs in this sample were created for demonstration.",
  ui: {
    facts: ["generations", "people in the tree", "towns", "stories"],
    back: "← Home", start: "Start your own book", prev: "Back", next: "Next", open: "Open the book",
    page: "Page", of: "of", hint: "Turn pages with the arrows, a swipe or the buttons", chapter: "Chapter", listen: "Scan to listen",
    eyebrow: "Sample book", lead: "This is what your family's book can look like: stories told by voice, the tree, the map of the family's road and photographs. Leaf through the book of the made-up Jones family.", cta: "Leaf through a sample book",
  },
};
export default en;
