import type { SampleBookText } from "./types";

const es: SampleBookText = {
  title: "Familia García",
  subtitle: "Siete generaciones de una familia",
  years: "1852 — 2026",
  motto: "Raíz honda, rama alta",
  crest: { shape: "heater", division: "plain", field: "vert", field2: "or", ordinary: "chief", ordinaryColor: "or", charges: ["tree", "sun", "sun"], chargeColor: "argent", motto: "" },
  dedication: "Para Lucía y Martín, para que sepan de dónde vienen.\nY para la abuela Pilar, que lo contó todo a tiempo.",
  contents: "Índice",
  treeTitle: "Nuestra línea",
  relatives: 63,
  treeNote: "La línea directa desde José García, jornalero en los olivares de Martos, hasta Lucía y Martín. En el árbol familiar hay sesenta y tres personas más: hermanos, hermanas, sus parejas y sus hijos.",
  line: [
    { h: ["José García", "1852–1920"], w: ["Dolores Pérez", "1856–1931"] },
    { h: ["Antonio García", "1882–1949"], w: ["Carmen López", "1886–1970"] },
    { h: ["Francisco García", "1912–1986"], w: ["Isabel Romero", "1915–2002"] },
    { h: ["Manuel García", "1940–2014"], w: ["Pilar Navarro", "1943–2021"] },
    { h: ["Javier García", "1967"], w: ["Montse Puig", "1969"] },
    { h: ["Pablo García", "1994"], w: ["Laura Martín", "1995"] },
  ],
  children: [["Lucía", "2020"], ["Martín", "2023"]],
  family: {
    caption: "Familia García, Martos, 1915",
    year: 1915, scene: "house",
    prompt: "Formal outdoor portrait of an Andalusian rural family in Jaén province in 1915: a father in a short jacket and a wide-brimmed hat, a mother in a black dress and shawl, four children, a whitewashed wall with a wooden door and a pot of geraniums behind.",
  },
  mapTitle: "El camino de la familia",
  mapNote: "De los olivares de Jaén a Barcelona en el tren de los emigrantes, y después a Madrid y Valencia: ciento setenta años de ida y vuelta.",
  stops: [
    { name: "Martos", label: "los olivares", lon: -3.97, lat: 37.72, year: 1852 },
    { name: "Barcelona", label: "la fábrica de la SEAT", lon: 2.17, lat: 41.39, year: 1962 },
    { name: "Madrid", label: "estudios y trabajo", lon: -3.7, lat: 40.42, year: 2016 },
    { name: "Valencia", label: "nuestra casa hoy", lon: -0.38, lat: 39.47, year: 2021 },
  ],
  recipe: {
    chapter: "Tradiciones",
    title: "Las torrijas de la abuela Pilar",
    who: "Pilar García, de soltera Navarro, 1943–2021",
    ingredientsTitle: "Necesitas",
    ingredients: ["1 barra de pan del día anterior", "1 litro de leche", "1 rama de canela", "la piel de un limón", "150 g de azúcar", "3 huevos", "aceite de oliva para freír", "canela molida"],
    text: "Calentar la leche con la canela, la piel de limón y la mitad del azúcar, y dejarla templar. Cortar el pan en rebanadas gruesas y empaparlas bien en la leche, sin que se rompan. Pasarlas por huevo batido y freírlas en aceite caliente hasta que estén doradas por los dos lados. Escurrirlas sobre papel y rebozarlas en azúcar con canela. Se comen frías, en Semana Santa, y no sobra ninguna.",
    note: "La abuela usaba el aceite de los olivos de Martos, que le mandaban en una garrafa cada invierno. Laura las hace ahora con Lucía, que se come el azúcar antes de que llegue a las torrijas.",
    prompt: "A plate of Spanish torrijas dusted with cinnamon sugar on a blue-and-white ceramic plate, a bottle of olive oil, a cinnamon stick, a lemon and an old handwritten recipe notebook on a rustic kitchen table. Warm afternoon light.",
  },
  stories: [
    {
      scene: "field", year: 1885, chapter: "Los orígenes", title: "El olivar", who: "José García, 1852–1920", caption: "Martos, 1885",
      prompt: "An olive harvest in Andalusia around 1885: rows of old olive trees on hills, men beating branches with long poles, women gathering olives from cloths on the ground, a donkey with baskets, a whitewashed village on a hill behind.",
      text: "El primer García del que sabemos el nombre, José, era jornalero en los olivares de Martos. Trabajaba de sol a sol en la recogida, de noviembre a febrero, y en verano segaba trigo donde lo llamaran. Nunca tuvo tierra propia, pero conocía cada olivo de la sierra por su nombre. De él nos ha quedado una vara de varear, guardada detrás de la puerta en casa de los abuelos.",
      quote: "El olivo no tiene prisa, y por eso dura.",
    },
    {
      scene: "village", year: 1908, chapter: "El amor", title: "La feria de San Bartolomé", who: "Antonio y Carmen García, 1908", caption: "Martos, 1908",
      prompt: "A village fair in Andalusia around 1908: a small square with whitewashed houses, paper lanterns, men in hats and short jackets, women in long skirts with fans, a guitar player, a horse decorated with tassels, evening light.",
      text: "Antonio conoció a Carmen en la feria del pueblo, bailando unas sevillanas que él no sabía bailar. Se casaron en 1908 y vivieron en una casa de dos habitaciones con patio, donde Carmen cultivaba geranios en latas de aceite. Tuvieron siete hijos. Carmen contaba que en el patio cabía toda la familia los domingos, y que cuando no cabía, se abría la puerta de la calle.",
    },
    {
      scene: "village", year: 1938, chapter: "Los años difíciles", title: "Las cartas", who: "Francisco e Isabel García, 1938", caption: "Martos, 1938",
      prompt: "A bundle of old handwritten letters tied with a faded ribbon on a wooden table next to a small photograph, a pair of reading glasses and a rosary, in a whitewashed room with a small window. Still life, 1930s.",
      text: "Durante la guerra Francisco estuvo casi tres años lejos de casa. Isabel le escribía cada semana, aunque muchas cartas no llegaban, y él guardaba las que sí en el bolsillo de la chaqueta hasta que se deshacían. En la familia nunca se habló mucho de aquellos años. Pero las cartas de Isabel, atadas con una cinta, siguen en una caja de membrillo en casa de la tía Encarna.",
      quote: "Lo importante es volver, lo demás ya se arreglará.",
    },
    {
      scene: "city", year: 1962, chapter: "La partida", title: "El tren a Barcelona", who: "Manuel García, 1940–2014", caption: "Estación de Francia, 1962",
      prompt: "A crowded railway platform at a Barcelona station in 1962: young Andalusian migrants with cardboard suitcases and bundles stepping off a long train, families waiting, a steam locomotive, high iron roof.",
      text: "En 1962 Manuel cogió el tren en Jaén con una maleta de cartón y un bocadillo de tortilla. Llegó a Barcelona después de veinte horas, sin conocer a nadie, y a la semana ya trabajaba en la fábrica de la SEAT en la Zona Franca. Vivió en una barraca en Montjuïc con otros paisanos hasta que se casó con Pilar, también de Jaén, a la que conoció en un baile para andaluces en el barrio.",
    },
    {
      scene: "field", year: 1968, chapter: "Los buenos años", title: "El Seiscientos", who: "Manuel y Pilar García, 1968", caption: "Costa Brava, 1968",
      prompt: "A small white SEAT 600 car parked by a Mediterranean beach on the Costa Brava in 1968, a young Spanish couple and a little boy having a picnic with a cooler and folding chairs, pine trees, bright summer light.",
      text: "El primer coche de la familia fue un Seiscientos blanco, comprado a plazos en 1968, del que Manuel había ayudado a montar las puertas. Los domingos iban a la Costa Brava con la tortilla, la sandía y la abuela. En verano bajaban al pueblo, mil kilómetros con el coche lleno hasta el techo, y Javier dormía encima de las maletas. La foto del coche cargado sigue en el aparador.",
    },
    {
      scene: "city", year: 1992, chapter: "La fiesta", title: "Las Olimpiadas", who: "Javier y Montse García, 1992", caption: "Barcelona, 1992",
      prompt: "Barcelona in the summer of 1992: volunteers in colourful uniforms near a stadium, crowds with flags, Montjuïc hill, a young couple laughing, bright sunlight.",
      text: "Javier y Montse se conocieron como voluntarios en los Juegos Olímpicos de 1992. Él repartía agua en el estadio de Montjuïc, a pocos metros de donde su padre había vivido en una barraca treinta años antes. Ella era de Gràcia y le enseñó catalán; él a ella, a hacer salmorejo. Se casaron dos años después, con una boda medio en castellano y medio en catalán, y con flamenco al final.",
      voice: "Escucha a Javier contarlo",
    },
    {
      scene: "city", year: 2018, chapter: "Hoy", title: "Madrid", who: "Pablo García, 1994", caption: "Madrid, 2018",
      prompt: "A Madrid street in 2018: a young couple with a bicycle outside a café with green tiles, apartment balconies with flowers, a red city bus, warm late afternoon light.",
      text: "Laura y yo nos conocimos en Madrid, en el máster, en una clase a la que los dos llegábamos tarde. Ella es de Valencia y yo de Barcelona, y el abuelo Manuel decía que por fin un García se iba a casar con alguien que entendía de paella. En 2021, cuando nació Lucía, nos mudamos a Valencia, cerca del mar y de sus padres.",
    },
    {
      scene: "house", year: 2024, chapter: "La nueva generación", title: "La voz de la abuela Pilar", who: "Pablo García, 1994", caption: "Valencia, 2024",
      prompt: "A bright Valencia apartment in the evening: a young father with a small girl and a toddler on a sofa looking at an old family photo album, a phone playing audio on the table, a plate of torrijas, warm lamp light.",
      text: "Un año antes de que muriera, grabé a la abuela Pilar con el móvil, tres tardes en su cocina de Barcelona. Contaba el tren de Jaén, la barraca, el Seiscientos y cómo el abuelo le cantaba boleros desafinando. Ahora Lucía pide «la historia de la bisabuela» antes de dormir. No la conoció, pero se ríe en los mismos sitios que yo.",
      voice: "La voz de la abuela Pilar, grabada en 2020",
    },
  ],
  endTitle: "Este libro es un ejemplo",
  endText: "Los García son inventados, pero el libro es real: así reúne Treename las historias que tu familia cuenta de viva voz, con el árbol, el mapa y las fotos. El tuyo se hará con vuestras propias historias.",
  colophon: "El libro de la familia García · hecho con Treename · 2026",
  photoNote: "La familia y las fotos de este ejemplo se han creado para la demostración.",
  ui: {
    facts: ["generaciones", "personas en el árbol", "ciudades", "historias"],
    back: "← Inicio", start: "Empezar mi libro", prev: "Atrás", next: "Siguiente", open: "Abrir el libro",
    page: "Página", of: "de", hint: "Pasa las páginas con las flechas, deslizando o con los botones", chapter: "Capítulo", listen: "Escanea y escucha",
    eyebrow: "Libro de ejemplo", lead: "Así puede ser el libro de tu familia: historias contadas de viva voz, el árbol, el mapa del camino familiar y fotos. Hojea el libro de la familia inventada García.", cta: "Hojear un libro de ejemplo",
  },
};
export default es;
