import type { SampleBookText } from "./types";

const fr: SampleBookText = {
  title: "Les Martin",
  subtitle: "Sept générations d'une même famille",
  years: "1849 — 2026",
  motto: "Le vent tourne, on reste",
  crest: { shape: "french", division: "plain", field: "azure", field2: "argent", ordinary: "bordure", ordinaryColor: "argent", charges: ["fish", "anchor", "fish"], chargeColor: "or", motto: "" },
  dedication: "Pour Léa et Hugo, afin qu'ils sachent d'où ils viennent.\nEt pour Mamie Monique, qui a tout raconté à temps.",
  contents: "Sommaire",
  treeTitle: "Notre lignée",
  relatives: 60,
  treeNote: "La lignée directe, d'Yves Martin, pêcheur à Douarnenez, jusqu'à Léa et Hugo. L'arbre de la famille compte encore soixante personnes : frères, sœurs, leurs conjoints et leurs enfants.",
  line: [
    { h: ["Yves Martin", "1849–1912"], w: ["Marie Le Gall", "1853–1925"] },
    { h: ["Jean Martin", "1877–1916"], w: ["Anne Kervella", "1880–1960"] },
    { h: ["Louis Martin", "1905–1978"], w: ["Jeanne Morel", "1908–1997"] },
    { h: ["Pierre Martin", "1934–2011"], w: ["Monique Fabre", "1937–2020"] },
    { h: ["Philippe Martin", "1963"], w: ["Nadia Benali", "1965"] },
    { h: ["Julien Martin", "1992"], w: ["Camille Roux", "1993"] },
  ],
  children: [["Léa", "2019"], ["Hugo", "2022"]],
  family: {
    caption: "Les Martin, Douarnenez, 1908",
    year: 1908, scene: "pier",
    prompt: "Formal outdoor portrait of a Breton fishing family in Douarnenez, 1908: a weathered fisherman with a beard and a sailor's cap, his wife in a traditional white Breton lace coiffe and black dress, a young man and two girls also in coiffes, fishing boats with sails in the harbour behind.",
  },
  mapTitle: "Le chemin de la famille",
  mapNote: "Du port de Douarnenez aux tranchées de Verdun, des usines de Billancourt à Lyon, puis retour vers l'Atlantique, à Nantes.",
  stops: [
    { name: "Douarnenez", label: "le port aux sardines", lon: -4.33, lat: 48.09, year: 1849 },
    { name: "Verdun", label: "la dernière lettre de Jean", lon: 5.38, lat: 49.16, year: 1916 },
    { name: "Paris", label: "les usines de Billancourt", lon: 2.24, lat: 48.83, year: 1925 },
    { name: "Lyon", label: "un ingénieur et ses traboules", lon: 4.84, lat: 45.76, year: 1962 },
    { name: "Nantes", label: "chez nous aujourd'hui", lon: -1.55, lat: 47.22, year: 2016 },
  ],
  recipe: {
    chapter: "Traditions",
    title: "Le far breton de Mamie Anne",
    who: "Anne Martin, née Kervella, 1880–1960",
    ingredientsTitle: "Il faut",
    ingredients: ["250 g de farine", "200 g de sucre", "4 œufs", "1 litre de lait entier", "50 g de beurre demi-sel", "250 g de pruneaux", "un petit verre de rhum, si on en a"],
    text: "Faire tremper les pruneaux dans le rhum la veille. Mélanger la farine et le sucre, ajouter les œufs un par un, puis le lait petit à petit pour éviter les grumeaux. Laisser reposer la pâte une heure. Beurrer généreusement le plat, y verser la pâte, répartir les pruneaux et quelques noisettes de beurre. Cuire une heure à four chaud, jusqu'à ce que le dessus soit bien doré et un peu craquelé.",
    note: "Anne le faisait sans pruneaux pendant la guerre, « parce que les pruneaux, c'était pour les enfants des autres ». Camille le fait aujourd'hui avec des abricots secs, et personne n'a encore osé lui dire que ce n'est pas un vrai far.",
    prompt: "A golden Breton far with prunes in a buttered earthenware dish on a rustic wooden table, a bowl of cider, a lace doily and an old handwritten recipe notebook. Soft coastal daylight.",
  },
  stories: [
    {
      scene: "pier", year: 1885, chapter: "Les origines", title: "Le port aux sardines", who: "Yves Martin, 1849–1912", caption: "Douarnenez, 1885",
      prompt: "The harbour of Douarnenez in Brittany around 1885: wooden sardine fishing boats with brown sails, fishermen unloading baskets of fish on the quay, women in white Breton coiffes, stone houses and a canning factory behind.",
      text: "Le premier Martin dont on connaît le nom, Yves, pêchait la sardine à Douarnenez. Il partait avant l'aube sur une chaloupe à deux mâts et rentrait le soir, quand les femmes attendaient sur le quai pour porter le poisson aux conserveries. Sa femme Marie y travaillait douze heures par jour. On a gardé d'Yves un couteau à manche de corne et une phrase que tout le monde répète encore à table.",
      quote: "La mer ne prête rien, elle rend parfois.",
    },
    {
      scene: "field", year: 1916, chapter: "Les années dures", title: "La lettre de Verdun", who: "Jean et Anne Martin, 1916", caption: "Verdun, 1916",
      prompt: "A French soldier's letter and an envelope with a field post stamp from 1916 lying on a wooden table next to an old photograph, a military button and a pocket watch. Soft window light, still life.",
      text: "Jean est parti en 1914 avec tous les hommes du port. Il écrivait à Anne chaque semaine, de petites lettres au crayon où il ne parlait jamais de la guerre, seulement de la mer et des enfants. La dernière est datée du 2 mars 1916, près de Verdun. Il y demandait si le petit Louis avait appris à nager. Anne a gardé cette lettre toute sa vie dans son missel, et elle est maintenant chez nous, dans une boîte en fer.",
    },
    {
      scene: "city", year: 1925, chapter: "Le départ", title: "Billancourt", who: "Louis Martin, 1905–1978", caption: "Billancourt, 1925",
      prompt: "The gates of a large car factory on the Seine near Paris around 1925: crowds of workers in caps and overalls arriving on foot and by bicycle, brick buildings, smoke from chimneys, a tram, a misty morning.",
      text: "À vingt ans, Louis a quitté la Bretagne pour Paris, où les usines automobiles cherchaient des bras. Il est entré à Billancourt et a passé trente ans sur la chaîne. Le dimanche, il allait danser au bord de la Marne, et c'est là qu'il a rencontré Jeanne, une couturière de Belleville qui se moquait de son accent. Ils se sont mariés en 1931 et ont vécu toute leur vie dans le même deux-pièces.",
    },
    {
      scene: "pier", year: 1936, chapter: "Le bonheur", title: "Les premiers congés", who: "Louis et Jeanne Martin, 1936", caption: "Plage de Trouville, 1936",
      prompt: "A crowded French beach in the summer of 1936: working-class families with children in old-fashioned swimsuits, men with rolled-up trousers, a tandem bicycle on the sand, striped tents, the sea and cliffs behind.",
      text: "En 1936, pour la première fois, l'usine a donné quinze jours de congés payés. Louis et Jeanne ont pris le train pour la mer avec un tandem acheté à crédit. Jeanne n'avait jamais vu l'océan. Ils ont dormi dans une grange et mangé des sardines grillées tous les soirs. Louis disait que, pour un Breton, c'était bien la peine de venir à Paris pour retourner voir la mer.",
      quote: "Quinze jours, et on se croyait riches.",
    },
    {
      scene: "city", year: 1944, chapter: "La guerre", title: "La Libération", who: "Pierre Martin, 1934–2011", caption: "Paris, août 1944",
      prompt: "A Paris street during the Liberation in August 1944: crowds waving French flags, people on balconies, a jeep, cobblestones, children running, joy and chaos, bright summer light.",
      text: "Pierre avait dix ans en août 1944. Pendant une semaine, sa mère lui avait interdit de sortir. Le jour où les cloches ont sonné dans tout Paris, il s'est échappé par la fenêtre et a couru jusqu'à l'Hôtel de Ville avec ses copains. Un soldat lui a donné une tablette de chocolat. Il a raconté cette histoire à chaque Noël, et le chocolat grandissait d'une année sur l'autre.",
    },
    {
      scene: "city", year: 1962, chapter: "L'amour", title: "Lyon et ses traboules", who: "Pierre et Monique Martin, 1962", caption: "Lyon, 1962",
      prompt: "A young couple walking through a narrow traboule passage in Old Lyon in 1962, stone arches and old staircases, the man in a suit, the woman in a full skirt and headscarf, a scooter parked nearby.",
      text: "Devenu ingénieur, Pierre a été envoyé à Lyon pour construire des barrages sur le Rhône. Monique, une Lyonnaise, lui a fait découvrir les traboules, ces passages secrets entre les immeubles du Vieux-Lyon. Il se perdait à chaque fois, et elle disait qu'elle l'avait épousé pour qu'il arrête de lui demander son chemin. Ils ont eu trois enfants et un vélo Solex pour toute la famille.",
    },
    {
      scene: "city", year: 1998, chapter: "La fête", title: "Le 12 juillet 1998", who: "Philippe et Nadia Martin, 1998", caption: "Lyon, 1998",
      prompt: "A crowded Lyon square on a summer night in 1998: people celebrating a football victory with French flags, car horns, a young couple carrying a small boy on their shoulders, street lights and fireworks.",
      text: "Philippe et Nadia se sont rencontrés à la fac de Lyon : lui faisait de la chimie, elle du droit, et leurs parents ne se connaissaient pas encore. Le soir de la finale de 1998, ils étaient sur la place Bellecour avec le petit Julien sur les épaules. Nadia dit que c'est la seule fois où les deux familles ont chanté ensemble la même chanson, chacune avec un accent différent.",
      voice: "Écoutez Philippe le raconter",
    },
    {
      scene: "house", year: 2024, chapter: "La génération suivante", title: "La voix de Mamie", who: "Julien Martin, 1992", caption: "Nantes, 2024",
      prompt: "A bright Nantes apartment in the evening: a young father with two small children on a sofa looking at an old family photo album, a phone playing audio on a low table, a slice of far breton, warm lamp light.",
      text: "Un an avant sa mort, j'ai enregistré Mamie Monique sur mon téléphone, trois après-midi de suite dans sa cuisine. Elle racontait les barrages, les traboules et les chansons de son père. Aujourd'hui Léa réclame « l'histoire de Mamie » avant de dormir. Elle ne l'a jamais connue, mais elle rit aux mêmes endroits que moi.",
      voice: "La voix de Mamie Monique, enregistrée en 2019",
    },
  ],
  endTitle: "Ce livre est un exemple",
  endText: "Les Martin sont inventés, mais le livre est bien réel : c'est ainsi que Treename rassemble les histoires que votre famille raconte de vive voix, avec l'arbre, la carte et les photos. Le vôtre sera fait de vos propres histoires.",
  colophon: "Le livre de la famille Martin · réalisé avec Treename · 2026",
  photoNote: "La famille et les photos de cet exemple ont été créées pour la démonstration.",
  ui: {
    facts: ["générations", "personnes dans l’arbre", "villes", "histoires"],
    back: "← Accueil", start: "Commencer mon livre", prev: "Précédent", next: "Suivant", open: "Ouvrir le livre",
    page: "Page", of: "sur", hint: "Tournez les pages avec les flèches, d'un geste ou avec les boutons", chapter: "Chapitre", listen: "Scannez pour écouter",
    eyebrow: "Livre exemple", lead: "Voici à quoi peut ressembler le livre de votre famille : des histoires racontées de vive voix, l'arbre, la carte du chemin familial et des photos. Feuilletez le livre de la famille inventée Martin.", cta: "Feuilleter un livre exemple",
  },
};
export default fr;
