import type { SampleBookText } from "./types";

const it: SampleBookText = {
  title: "Famiglia Esposito",
  subtitle: "Sette generazioni di una famiglia",
  years: "1850 — 2026",
  motto: "Dove c'è sole, c'è casa",
  crest: { shape: "heater", division: "plain", field: "azure", field2: "or", ordinary: "none", ordinaryColor: "argent", charges: ["sun", "leaf", "leaf"], chargeColor: "or", motto: "" },
  dedication: "Per Sofia e Leonardo, perché sappiano da dove vengono.\nE per nonna Lucia, che ha raccontato tutto in tempo.",
  contents: "Indice",
  treeTitle: "La nostra linea",
  relatives: 64,
  treeNote: "La linea diretta da Gennaro Esposito, contadino tra i limoni di Sorrento, fino a Sofia e Leonardo. Nell'albero di famiglia ci sono altre sessantaquattro persone: fratelli, sorelle, mogli, mariti e figli.",
  line: [
    { h: ["Gennaro Esposito", "1850–1918"], w: ["Carmela Russo", "1855–1930"] },
    { h: ["Salvatore Esposito", "1880–1950"], w: ["Assunta Gallo", "1884–1962"] },
    { h: ["Antonio Esposito", "1915–1990"], w: ["Rosa Ferrara", "1919–2005"] },
    { h: ["Vincenzo Esposito", "1942–2015"], w: ["Lucia Conti", "1945–2022"] },
    { h: ["Marco Esposito", "1968"], w: ["Paola Bianchi", "1970"] },
    { h: ["Luca Esposito", "1995"], w: ["Giulia Romano", "1996"] },
  ],
  children: [["Sofia", "2021"], ["Leonardo", "2024"]],
  family: {
    caption: "Famiglia Esposito, Sorrento, 1913",
    year: 1913, scene: "house",
    prompt: "Portrait of a southern Italian peasant family near Sorrento in 1913: a moustached father in a waistcoat and hat, a mother in a dark dress and shawl, three children barefoot and in their Sunday best, lemon trees on a terrace and a stone wall behind.",
  },
  mapTitle: "Il cammino della famiglia",
  mapNote: "Dai limoneti di Sorrento a New York e ritorno, da Napoli a Torino con il Treno del Sole, e infine a Milano.",
  stops: [
    { name: "Sorrento", label: "i limoni sulla collina", lon: 14.37, lat: 40.63, year: 1850 },
    { name: "Napoli", label: "il vicolo e il matrimonio", lon: 14.27, lat: 40.85, year: 1938 },
    { name: "Torino", label: "la FIAT di Mirafiori", lon: 7.69, lat: 45.07, year: 1961 },
    { name: "Milano", label: "oggi casa nostra", lon: 9.19, lat: 45.46, year: 2019 },
  ],
  side: { label: "New York, 1906 →", dir: "w", from: 0 },
  recipe: {
    chapter: "Tradizioni",
    title: "Il ragù della domenica di nonna Rosa",
    who: "Rosa Esposito, nata Ferrara, 1919–2005",
    ingredientsTitle: "Serve",
    ingredients: ["800 g di carne di manzo in un pezzo", "4 salsicce", "1 cipolla", "2 litri di passata di pomodoro", "un bicchiere di vino rosso", "olio d'oliva", "basilico", "sale", "pazienza"],
    text: "Si comincia la domenica mattina presto. Soffriggere la cipolla nell'olio in una pentola di coccio, rosolare bene la carne e le salsicce, sfumare con il vino. Aggiungere la passata e un po' d'acqua, coprire a metà e lasciare «pippiare» — cioè sobbollire appena — per almeno sei ore, mescolando ogni tanto con il cucchiaio di legno. Il sugo condisce i ziti, la carne si mangia dopo.",
    note: "Nonna Rosa diceva che il ragù non si cucina, si aspetta. Paola lo fa ancora ogni prima domenica del mese, e Luca ruba il pane da intingere prima di pranzo, come faceva suo padre.",
    prompt: "A big terracotta pot of Neapolitan ragù simmering on an old stove, a wooden spoon, a plate of ziti pasta, basil, a loaf of bread and an old handwritten recipe notebook on a kitchen table. Warm Sunday morning light.",
  },
  stories: [
    {
      scene: "village", year: 1885, chapter: "Le origini", title: "I limoni di Sorrento", who: "Gennaro Esposito, 1850–1918", caption: "Sorrento, 1885",
      prompt: "Lemon groves on terraces above the sea near Sorrento around 1885: wooden pergolas covered with straw mats, peasants carrying baskets of lemons, a stone farmhouse, the Bay of Naples and Vesuvius in the haze.",
      text: "Il primo Esposito di cui conosciamo il nome, Gennaro, coltivava i limoni sulle terrazze sopra Sorrento. D'inverno copriva gli alberi con stuoie di paglia per proteggerli dal freddo, e d'estate portava le ceste giù al porto a spalla. Sua moglie Carmela faceva il rosolio con le bucce. In casa si conserva ancora la sua roncola, con il manico consumato dalla mano.",
      quote: "Chi semina limoni, raccoglie sole.",
    },
    {
      scene: "pier", year: 1906, chapter: "La partenza", title: "L'America e ritorno", who: "Salvatore Esposito, 1880–1950", caption: "Napoli, porto, 1906",
      prompt: "The port of Naples in 1906: a large steamship with two funnels at the quay, crowds of emigrants with trunks and bundles, women in shawls, men in caps, a gangway, smoke and haze.",
      text: "Nel 1906 Salvatore si imbarcò a Napoli per New York con un baule di legno e l'indirizzo di un cugino. Lavorò sette anni a Brooklyn, posando binari e mandando a casa i dollari dentro le lettere. Nel 1913 tornò, comprò un pezzo di terra accanto a quella del padre e sposò Assunta, che lo aveva aspettato. Dall'America portò un orologio da tasca e una parola che in famiglia si usa ancora: «okay».",
    },
    {
      scene: "city", year: 1938, chapter: "L'amore", title: "Il vicolo di Napoli", who: "Antonio e Rosa Esposito, 1938", caption: "Napoli, 1938",
      prompt: "A narrow alley in old Naples in 1938: laundry hanging between balconies, a small shrine on the wall, children playing, a woman lowering a basket on a rope from a window, cobblestones, strong light and shadows.",
      text: "Antonio andò a Napoli a fare il garzone in una bottega di sarto, e ogni mattina passava sotto il balcone di Rosa. Lei calava il paniere con la corda per comprare il pane, e lui un giorno ci mise dentro un biglietto. Si sposarono nel 1938 nella chiesa del quartiere. Il paniere di vimini è rimasto in famiglia: oggi ci teniamo le foto vecchie.",
    },
    {
      scene: "city", year: 1943, chapter: "La guerra", title: "Napoli, 1943", who: "Rosa Esposito, 1919–2005", caption: "Napoli, 1943",
      prompt: "A damaged Naples street in 1943: rubble from bombing, women with children carrying bundles, a tram stopped in the street, laundry still on a balcony, smoke in the distance, grey light.",
      text: "Durante i bombardamenti Rosa scendeva nei ricoveri sotto il tufo con il piccolo Vincenzo in braccio e una pentola di fagioli. Antonio era lontano, al fronte, e per due anni non arrivarono notizie. Quando a settembre 1943 la città si liberò, Rosa uscì in strada con le vicine e pianse per tutto il giorno. Antonio tornò a casa nel 1945, a piedi, con le scarpe legate con lo spago.",
      quote: "Finché c'è una pentola sul fuoco, c'è speranza.",
    },
    {
      scene: "city", year: 1961, chapter: "La partenza", title: "Il Treno del Sole", who: "Vincenzo Esposito, 1942–2015", caption: "Torino, 1961",
      prompt: "A crowded railway platform at Turin Porta Nuova station in 1961: young southern Italian men with cardboard suitcases tied with string stepping off a long train, a steam of breath in cold air, a big station clock.",
      text: "A diciannove anni Vincenzo prese il Treno del Sole da Napoli a Torino: diciotto ore seduto sulla valigia di cartone. La FIAT cercava operai, e lui entrò a Mirafiori il giorno dopo. Per mesi dormì in una soffitta con altri quattro ragazzi del Sud. Nel 1965 conobbe Lucia, piemontese, a un ballo in parrocchia. Lei rideva del suo accento, lui della polenta di sua madre.",
    },
    {
      scene: "field", year: 1966, chapter: "Gli anni belli", title: "La Seicento", who: "Vincenzo e Lucia Esposito, 1966", caption: "Liguria, 1966",
      prompt: "A small white FIAT 600 parked on a coastal road in Liguria in 1966, a young Italian couple and a toddler having a picnic beside it, the sea below, pine trees, bright summer light.",
      text: "Nel 1966 comprarono una Seicento bianca a rate. La domenica caricavano la macchina — Vincenzo, Lucia, il piccolo Marco, la nonna, due sedie pieghevoli e la pentola del ragù — e partivano verso il mare della Liguria. Una volta si ruppe sulla salita del Turchino e la spinsero tutti insieme, nonna compresa. Quella foto è appesa in cucina ancora oggi.",
    },
    {
      scene: "city", year: 1994, chapter: "Il lavoro", title: "Gli anni Novanta", who: "Marco Esposito, 1968", caption: "Torino, 1994",
      prompt: "A Turin apartment in 1994: a young couple painting the walls of their first flat, a small boy sitting on newspapers on the floor, a radio, ladders, sunlight through tall windows.",
      text: "Io e Paola ci siamo conosciuti all'università di Torino. Lei studiava architettura, io ingegneria, e la nostra prima casa l'abbiamo ridipinta da soli in un weekend, con Luca in mezzo alla vernice. Papà Vincenzo veniva ogni sabato a controllare i lavori e a dire che al Sud si faceva tutto meglio. Poi si fermava a cena e rimaneva fino a mezzanotte.",
      voice: "Ascoltate Marco che lo racconta",
    },
    {
      scene: "house", year: 2024, chapter: "La nuova generazione", title: "La voce di nonna Lucia", who: "Luca Esposito, 1995", caption: "Milano, 2024",
      prompt: "A bright Milan apartment in the evening: a young father with a small girl and a baby on a sofa looking at an old family photo album, a phone playing audio on the table, warm lamp light.",
      text: "Due anni prima che morisse, ho registrato nonna Lucia con il telefono, nella sua cucina di Torino, per tre pomeriggi. Raccontava del ballo in parrocchia, della Seicento e di come il nonno le cantava Modugno stonando. Ora Sofia vuole sentire «la storia della bisnonna» prima di dormire. Non l'ha mai conosciuta, ma ride negli stessi punti in cui rido io.",
      voice: "La voce di nonna Lucia, registrata nel 2020",
    },
  ],
  endTitle: "Questo libro è un esempio",
  endText: "Gli Esposito sono inventati, ma il libro è vero: è così che Treename raccoglie le storie che la vostra famiglia racconta a voce, con l'albero, la mappa e le fotografie. Il vostro nascerà dalle vostre storie.",
  colophon: "Il libro della famiglia Esposito · realizzato con Treename · 2026",
  photoNote: "La famiglia e i disegni di questo esempio sono stati inventati a scopo dimostrativo.",
  ui: {
    facts: ["generazioni", "persone nell’albero", "città", "storie"],
    back: "← Home", start: "Inizia il tuo libro", prev: "Indietro", next: "Avanti", open: "Apri il libro",
    page: "Pagina", of: "di", hint: "Sfoglia con le frecce, con un gesto o con i pulsanti", chapter: "Capitolo", listen: "Inquadra e ascolta",
    eyebrow: "Libro di esempio", lead: "Ecco come può essere il libro della vostra famiglia: storie raccontate a voce, l'albero, la mappa del cammino e le fotografie. Sfogliate il libro dell'immaginaria famiglia Esposito.", cta: "Sfoglia un libro di esempio",
  },
};
export default it;
