import type { SampleBookText } from "./types";

const ru: SampleBookText = {
  title: "Ивановы",
  subtitle: "Семь поколений одной семьи",
  years: "1851 — 2026",
  motto: "Что посеешь, то и пожнёшь",
  crest: { shape: "heater", division: "plain", field: "vert", field2: "or", ordinary: "chief", ordinaryColor: "argent", charges: ["wheat", "sun", "wheat"], chargeColor: "or", motto: "" },
  dedication: "Маше и Ване — чтобы знали, откуда они.\nИ бабушке Гале, которая успела рассказать.",
  contents: "Содержание",
  treeTitle: "Наш род",
  relatives: 62,
  treeNote: "Прямая линия от Степана Иванова из деревни Покровское до Маши и Вани. В семейном древе — ещё шестьдесят два человека: братья, сёстры, их мужья, жёны и дети.",
  line: [
    { h: ["Степан Иванов", "1851–1919"], w: ["Агафья Иванова", "1855–1924"] },
    { h: ["Пётр Иванов", "1879–1942"], w: ["Мария Соколова", "1883–1950"] },
    { h: ["Николай Иванов", "1908–1985"], w: ["Анна Кузнецова", "1912–1999"] },
    { h: ["Виктор Иванов", "1936–2012"], w: ["Галина Орлова", "1939–2018"] },
    { h: ["Сергей Иванов", "1962"], w: ["Ольга Белова", "1965"] },
    { h: ["Дмитрий Иванов", "1989"], w: ["Катерина Сафина", "1991"] },
  ],
  children: [["Маша", "2016"], ["Ваня", "2019"]],
  family: {
    caption: "Ивановы, Петербург, 1912",
    year: 1912, scene: "house",
    prompt: "Portrait of a Russian working family in St Petersburg, 1912: a moustached father in a dark jacket and peaked cap standing, a mother in a long skirt and blouse seated, two boys in belted shirts and a little girl with a bow.",
  },
  mapTitle: "Путь семьи",
  mapNote: "Из тверской деревни — на завод в Петербург, в войну — на Урал, потом в Москву. Сто семьдесят пять лет и почти три тысячи километров.",
  stops: [
    { name: "Покровское", label: "изба, которую ставили всей деревней", lon: 35.6, lat: 57.1, year: 1851 },
    { name: "Петербург", label: "Путиловский завод", lon: 30.32, lat: 59.94, year: 1898 },
    { name: "Челябинск", label: "эвакуация вместе с заводом", lon: 61.4, lat: 55.16, year: 1941 },
    { name: "Москва", label: "институт, потом своя семья", lon: 37.62, lat: 55.76, year: 1984 },
    { name: "Казань", label: "здесь Дима встретил Катю", lon: 49.12, lat: 55.79, year: 2011 },
  ],
  recipe: {
    chapter: "Традиции",
    title: "Пирог с капустой бабушки Анны",
    who: "Анна Иванова, урождённая Кузнецова, 1912–1999",
    ingredientsTitle: "Что нужно",
    ingredients: ["500 г муки", "250 мл тёплого молока", "10 г дрожжей", "2 яйца", "50 г масла", "1 кг капусты", "1 луковица", "3 варёных яйца для начинки", "соль, сахар — по вкусу"],
    text: "Тесто ставили с вечера, накрыв полотенцем, на печку. Капусту мелко рубили, тушили с луком до мягкости, добавляли рубленые яйца. Тесто делили на две части: одну раскатать на противень, выложить начинку, накрыть второй, края защипать «косичкой». Смазать желтком, проколоть вилкой и печь, пока верх не станет как самовар.",
    note: "В Челябинске капусту меняли на хлебные карточки — пирог пекли раз в год, на Новый год. Сейчас его печёт Ольга, а Маша защипывает края.",
    prompt: "A homemade Russian cabbage pie with a braided crust on a dark baking tray, on a kitchen table with an embroidered linen towel, a cup of tea in a glass holder and an old handwritten recipe notebook. Warm window light.",
  },
  stories: [
    {
      scene: "village", year: 1884, chapter: "Истоки", title: "Изба в Покровском", who: "Степан Иванов, 1851–1919", caption: "Покровское, 1884",
      prompt: "A Russian village street in Tver province in the 1880s: log izbas with carved window frames, a muddy road, a wooden well with a long lever, a horse cart, peasants in kaftans and headscarves, birch trees.",
      text: "Самый старший Иванов, о котором мы знаем, — Степан, крестьянин из деревни Покровское под Тверью. Избу он ставил «помочью»: мужики со всей деревни рубили сруб за три дня, а хозяйка кормила их щами и пирогами. В углу под образами Степан вырезал на бревне год — 1884. Изба простояла больше ста лет, и бревно с датой правнук Виктор увёз на дачу, где оно лежит до сих пор.",
      quote: "Дом — не стены, дом — кто в нём живёт.",
    },
    {
      scene: "city", year: 1900, chapter: "Дорога", title: "На заработки в Петербург", who: "Пётр Иванов, 1879–1942", caption: "Путиловский завод, 1900",
      prompt: "The gate of a large factory in St Petersburg around 1900: brick workshops, tall chimneys with smoke, workers in caps and long coats walking in, a horse tram on the street, cobblestones, overcast sky.",
      text: "В девятнадцать лет Пётр ушёл из деревни «на отход» — в Петербург, на Путиловский завод. Жил в казарме на двенадцать коек, работал по одиннадцать часов и каждый месяц отправлял домой три рубля почтовым переводом. Писать он не умел, письма за него писал товарищ по койке, а в конце Пётр сам старательно выводил: «Кланяюсь всем. Петя». Одно такое письмо хранится в семье.",
    },
    {
      scene: "village", year: 1904, chapter: "Любовь", title: "Свадьба на Покров", who: "Пётр и Мария Ивановы, 1904", caption: "Покровское, 1904",
      prompt: "A Russian village church of white stone with a green onion dome in autumn, around 1904, a small wedding party in front: women in embroidered sarafans and headscarves, men in caftans, a decorated horse cart with ribbons, yellow birch leaves.",
      text: "На Покров Пётр приехал в деревню и посватался к Маше Соколовой с соседнего конца. Венчались в той же покровской церкви, где крестили обоих. Приданое уместилось в один сундук: две перины, самовар и вышитые полотенца — одно из них, с петухами, теперь висит у Ольги на кухне. После свадьбы Мария уехала с мужем в Петербург и всю жизнь вспоминала, как впервые увидела электрический фонарь.",
    },
    {
      scene: "city", year: 1941, chapter: "Трудные годы", title: "Эвакуация", who: "Николай и Анна Ивановы, 1941", caption: "Челябинск, 1941",
      prompt: "A freight train with factory machinery on open wagons and people in coats at a snowy Ural railway station in 1941, steam locomotive, wooden station building, crates, women with bundles, grey winter light.",
      text: "Осенью сорок первого цех Николая вывезли из Ленинграда на Урал — станки ехали на платформах, люди в теплушках. Анна с пятилетним Витей ехала следом почти месяц. В Челябинске завод запустили прямо под открытым небом, стены достраивали уже зимой. Николай работал по две смены и спал в цеху, Анна стояла в очередях с карточками. Витя потом говорил, что запомнил оттуда только мороз и запах машинного масла.",
      quote: "Всё для фронта — и одна картошина на троих.",
    },
    {
      scene: "house", year: 1962, chapter: "Свой дом", title: "Первая квартира", who: "Виктор и Галина Ивановы, 1962", caption: "Челябинск, 1962",
      prompt: "A newly built five-storey Soviet apartment block (khrushchevka) in 1962, young trees, a courtyard with a sandbox and washing lines, a young couple carrying a box and a rubber plant, a moving truck.",
      text: "Виктор и Галина познакомились на танцах в заводском клубе, поженились через полгода и четыре года жили у его родителей за шкафом. В шестьдесят втором завод дал им однокомнатную квартиру в новой пятиэтажке. Мебели не было, спали на матрасе, а первой покупкой стал телевизор «Рекорд» — смотреть его приходили соседи со всего подъезда. Галина говорила, что это были самые счастливые четыре стены в её жизни.",
    },
    {
      scene: "field", year: 1978, chapter: "Традиции", title: "Шесть соток", who: "Галина Иванова, 1939–2018", caption: "Дача, 1978",
      prompt: "A Soviet dacha garden plot in the late 1970s: a small wooden house painted green, potato rows, apple trees, a family of three generations digging potatoes with buckets, a boy with a dog, summer light.",
      text: "Дачу получили в семьдесят восьмом — шесть соток глины в сорока минутах на электричке. Виктор сам сколотил домик из ящиков от станков, Галина посадила яблони. Каждую осень вся семья копала картошку, а вечером варили варенье в медном тазу, и Серёжа отгонял ос. Бревно с датой из покровской избы до сих пор лежит у крыльца — на нём сидят, когда пьют чай.",
    },
    {
      scene: "city", year: 1993, chapter: "Отъезд", title: "Девяностые", who: "Сергей Иванов, 1962", caption: "Москва, 1993",
      prompt: "A Moscow street market in 1993: rows of kiosks, people in leather jackets and fur hats, a trolleybus, snow on the ground, a man selling electronics from a folding table, grey sky.",
      text: "Я приехал в Москву учиться в восемьдесят четвёртом, а в девяносто третьем мы с Олей уже растили Диму в съёмной комнате. Днём я был инженером в институте, где по три месяца не платили зарплату, а по вечерам чинил телевизоры. Оля вязала свитера на продажу. Было трудно, но смешно: однажды мы полгода копили на видеомагнитофон, а смотрели на нём одну кассету — «Иронию судьбы».",
      voice: "Послушайте, как это рассказывает Сергей",
    },
    {
      scene: "house", year: 2024, chapter: "Следующее поколение", title: "Бабушкин голос", who: "Дмитрий Иванов, 1989", caption: "Москва, 2024",
      prompt: "A modern Moscow apartment kitchen in the evening: a young father and his two small children at a table looking at an old photo album, a smartphone playing audio, a cup of tea and a plate of pie, warm lamp light.",
      text: "За год до смерти бабушка Галя согласилась, чтобы я записал её рассказы на телефон. Мы сидели на кухне три вечера: она рассказывала про эвакуацию, про первую квартиру и про то, как дед Витя за ней ухаживал. Теперь Маша просит включить «бабушкину сказку» перед сном. Она никогда не видела прабабушку, но знает её голос и смеётся в тех же местах, что и я.",
      voice: "Голос бабушки Гали, запись 2017 года",
    },
  ],
  endTitle: "Эта книга — пример",
  endText: "Ивановы придуманы, а книга настоящая: так Treename собирает истории, которые ваши родные рассказывают голосом, древо, карту и фотографии. Вашу книгу мы соберём из ваших историй.",
  colophon: "Семейная книга Ивановых · собрана в Treename · 2026",
  photoNote: "Семья и рисунки в этом примере придуманы для демонстрации.",
  ui: {
    facts: ["поколений", "человек в древе", "городов и сёл", "историй"],
    back: "← На главную", start: "Начать свою книгу", prev: "Назад", next: "Дальше", open: "Открыть книгу",
    page: "Страница", of: "из", hint: "Листайте стрелками, свайпом или кнопками", chapter: "Глава", listen: "Сканируйте и слушайте",
    eyebrow: "Пример книги", lead: "Так может выглядеть книга вашей семьи: истории, рассказанные голосом, древо, карта пути и фотографии. Полистайте книгу выдуманной семьи Ивановых.", cta: "Полистать пример книги",
  },
};
export default ru;
